"""Describe your change

Revision ID: 8dcf1a19c7f3
Revises: c0f29b971c4d
Create Date: 2025-07-10 14:14:32.338038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dcf1a19c7f3'
down_revision = 'c0f29b971c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_expl_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_column('extra_expl_count')

    # ### end Alembic commands ###
