"""Add awaiting_quiz_confirmation to Progress

Revision ID: c0f29b971c4d
Revises: 8d1ec87b491a
Create Date: 2025-07-10 13:54:06.244290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f29b971c4d'
down_revision = '8d1ec87b491a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('awaiting_quiz_confirmation', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_column('awaiting_quiz_confirmation')

    # ### end Alembic commands ###
