"""Describe your changes

Revision ID: dadf1d83d8f9
Revises: 8dcf1a19c7f3
Create Date: 2025-07-10 18:21:10.863343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dadf1d83d8f9'
down_revision = '8dcf1a19c7f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_type', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_column('quiz_type')

    # ### end Alembic commands ###
